export const TASK_CATEGORY_LABELS = {
  WORK: "Trabalho",
  STUDY: "Educação",
  HOME: "Casa",
  HEALTH_AND_WELLNESS: "Saúde e Bem-Estar",
  FINANCIAL: "Finanças",
  LEISURE: "Lazer",
  RELATIONSHIPS: "Relacionamentos",
  VOLUNTEERING: "Voluntariado",
  TRAVEL: "Viagens e Transporte",
  PERSONAL_DEVELOPMENT: "Desenvolvimento Pessoal",
  TECHNOLOGY: "Tecnologia",
  SHOPPING: "Compras",
  ERRANDS: "Compromissos",
  OTHER: "Outros",
};
