import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { SidebarProvider } from "../_components/ui/sidebar";
import { AppSidebar } from "../_components/app-sidebar";
import { ptBR } from "@clerk/localizations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
      >
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
          localization={ptBR}
        >
          <SidebarProvider>
            <AppSidebar />
            {children}
          </SidebarProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
